# El puerto principal por donde entrará TODA la aplicación (Frontend)
server.port=8080

# Nombre de la aplicación
spring.application.name=api-gateway

# Dónde está nuestro jefe (Eureka)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Conexión al Config-Server (Opcional por ahora, pero buena práctica)
spring.config.import=optional:configserver:http://localhost:8888

# --- LA MAGIA DEL ENRUTAMIENTO AUTOMÁTICO ---
# Le dice al Gateway que cree rutas automáticamente usando los nombres de Eureka
spring.cloud.gateway.discovery.locator.enabled=true
# Convierte los nombres de Eureka (ej. SECURITY-SERVICE) a minúsculas en la URL
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
# --- RUTAS PERSONALIZADAS CON EL FILTRO JWT ---
# Le decimos al Gateway: Si alguien pide la ruta /customer/**, pásalo por el Filtro y mándalo al Customer-Service
spring.cloud.gateway.routes[0].id=customer-service
spring.cloud.gateway.routes[0].uri=lb://CUSTOMER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/customer/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter