# El puerto donde vivirá nuestro servicio de seguridad
server.port=9000

# El nombre oficial del servicio (¡Vital para que el Config-Server lo reconozca!)
spring.application.name=security-service

# 1. Regístrate en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 2. Conéctate al Config-Server para descargar el resto de configuraciones
spring.config.import=optional:configserver:http://localhost:8888