# Puerto del servidor Eureka
server.port=8761

# Nombre del microservicio
spring.application.name=discovery-server

# Configuraciones de Eureka
# NO se registre a sí mismo
eureka.client.register-with-eureka=false

# NO intente obtener la lista de servicios desde otro lado
eureka.client.fetch-registry=false

# URL por defecto para el cliente (aunque sea el servidor)
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# --- SOLUCIÓN AL ERROR DE CONFIG SERVER ---
# Desactiva la conexión obligatoria al Config Server
spring.cloud.config.enabled=false
# Evita que el sistema falle si no encuentra la propiedad de importación
spring.cloud.config.import-check.enabled=false