# Configuración del Servidor
server.port=8083
spring.application.name=invoice-service

# Conexión a Base de Datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/billingflow_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Formato de respuesta JSON (opcional para ver fechas bonitas en consola)
spring.jackson.serialization.write-dates-as-timestamps=false