# Puerto por defecto
server.port=8888

# Nombre del servicio
spring.application.name=config-server

# URL de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- CONFIGURACIÓN DE GIT (REPOSITORIO PRIVADO) ---
spring.profiles.active=git

# 1. Tu URL de GitHub (fíjate que sea la HTTPS que termina en .git)
spring.cloud.config.server.git.uri=https://github.com/adrianmunozcasas-commits/config-server.git

# 2. Tu nombre de usuario de GitHub (ejemplo: juanperez99)
spring.cloud.config.server.git.username=adrianmunozcasas-commits

# 3. El Token que acabas de copiar (empieza por ghp_...)
spring.cloud.config.server.git.password=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

# Clona el repo al arrancar
spring.cloud.config.server.git.clone-on-start=true